### ISSUE TITLE
Show map - CORS header missing

### ISSUE THREAD

**Issue by drhirn** [dgiese/dustcloud#108]
Although there is this _enable_cors_-function in server.py, my browser won't show the actual map because:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://dustcloud.****:1121/get_map?did=64****. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 

Did I do something wrong? Or any idea, how I could fix this?

Edit - Some more information
When trying to open above page in a browser, it results in 404.
I'm running server.py with `./server.sh -sport 8080` and the command-server is defined as `http://dustcloud.****:1121` in config.php

**Comment by JackGruber** [comment]
Hi,

do you use different IPs/Names for the commandserver and Dustcloud user Interface (PHP Modules)?

404 Error
Habe you start your server.py with --enable-live-map ?

**Comment by drhirn** [comment]
> Habe you start your server.py with --enable-live-map ?

Ouch, no I didn't....
Thanks a lot!

Another question: Why do I get a permission denied when running server.py as wwwroot? No matter which ports I am using.

`Traceback (most recent call last):
  File "server.py", line 836, in <module>
    server = TCPSimpleServer(("0.0.0.0", server_port), SingleTCPHandler)
  File "server.py", line 702, in __init__
    socketserver.TCPServer.__init__(self, server_address, request_handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied`

Running as root is working.

**Comment by JackGruber** [comment]
Only root can bind ports below 1024 

you can allow python to bin ports below 1024 with
setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/python3.5

**Comment by drhirn** [comment]
I know. That's why I tried to start it with `./server.sh -sport 8080 -cmdport 11111 --enable-live-map`. Still the same error.
